### ISSUE TITLE
04강 gazebo simulation 소개 

### ISSUE THREAD

**Issue by miercat0424** [Road-Balance/gcamp_ros2_basic#1]
좋은영상 감사합니다. 현재 windows 10 에서 강의를 시청중인데 
3강 foxy 까지 설치하고 , gazebo 가상환경 생성 후 커맨드로 로봇 움직이기 까지 전부 잘 작동했습니다. 

Q1. 2:00에 서 나오는 cbp 커맨드는 Windows에서 지원이 안되나요 ?
----------------------------------------------------------------------------------
03강의 영상의 설치하는 과정중 따로 본적이 없는거 같습니다. 

Q2. powershell 에서는 colcon build를 할 수 없나요 ?
----------------------------------------------------------------------------------
ps1 에서 오류가 났고 , ros2_foxy 터미널에서 colcon build 하니까 됐습니다.

Q3. Windows 에서 gazebo 명령어를 환경변수에 넣어주고 싶은데 어떻게 다운받으면 될까요 ?
------------------------------------------------------------------------------------
mac을 사용할때 ros-noetic 에서는 terminal에서 gazebo 하면 바로 창이 업로드 됐습니다만 
03강에서 진행해 주신 방법의 ros2-foxy 에서는 gazebo.exe 파일을 못찾겠습니다. 

___________________________________________________________________________________________________
04강 6:29초 에서 gazebo.exe 파일을 찾을 수 없습니다.  
cmd 에서 gz , gzclient , gzserver 등 다양한 시도를 해보았지만 전부 오류가 나고 창이 뜨지않습니다. 

03 강에서 보여주셨던 방법을 응용해
 ros2 launch gcamp_gazebo empty_world.launch 를 사용해도 
비어있는 world가 아닌 튜토리얼에서 제시해 주셨던 환경이 나옵니다. 
매번 번거롭게 ros2 launch ... 하고 열린 gazebo 창에서 New File 을 하는건 너무 번거로워서
gazebo.exe 설치를 공식홈페이지에서 제시된 방법 gz_ws 디렉토리로 설치해도 문제없는지 묻고싶습니다.)
https://www.youtube.com/watch?v=edDy97z-o8g&t=121s

**Comment by kimsooyoung** [comment]
현재 windows 상에서의 개발은 제한점이 다소 있습니다.

우선, 간략한 답변을 남깁니다. 

1. 네 다만 지원이 안된다기보다, 제가 윈도우상에서 해보지 못하였습니다. 직접 해보시는 것을 추천드립니다.
2. 네, 일반 `powershell`에서는 오류가 날 것입니다.
3. 강의를 따라오셨다면,  `C:\opt\ros\foxy\x64\bin`에 `gzclient`, `gzserver`가 위치할 것입니다. 
4. windows 라면 3번 질문과 같이 환경변수에 추가해주셔야 할 것 같습니다.
5. 네, 현재 empty_world에도 기존 튜토리얼 환경이 나올 것입니다. 완전히 빈 gazebo 환경을 불러오고 싶다면, 다음 링크를 참조 바랍니다.
https://github.com/ros-simulation/gazebo_ros_pkgs/tree/dashing/gazebo_ros/launch

launch 파일에 대한 이해를 필요로 하기에 후반 강의 시청을 추천드립니다.

>  gazebo.exe 설치를 공식홈페이지에서 제시된 방법 gz_ws 디렉토리로 설치해도 문제없는지 묻고싶습니다.)

시도해보지 않았기에 결론을 드릴 수는 없으며, 수많은 환경변수 세팅을 직접 수동으로 해줘야 할 수도 있어 추천하진 않습니다.

**Comment by miercat0424** [comment]
ROS2도 Windows의 개발환경에서는 제한점이 있다는 정보 감사합니다. 
다른 번호들은 지금 시도를 못 해보지만 ,

답변해주신 3.4. 번의 C:\opt\ros\foxy\x64\bin 환경변수는 설정이 된 상태로 ,
해당 디렉토리에는 gazebo.exe가 존재 하지 않아 cmd창에서 gazebo를 명령해줄 시에
없는 명령어로 처리가 된걸로 보입니다.

gzclient나 gzserver는 말씀해주신대로 error가 발생하지않는데,
혹시나 해서 gzclient를 실행하고 분할 터미널에서 gzserver를 따로따로 실행하자 
처음 로딩할때 보이는 gazebo 주황색 로고만 나오고 프로그램이 정지했습니다.

답변 감사합니다 !

**Comment by miercat0424** [comment]
GPU를 WSL2 에서 사용가능하다 하여 해결됐습니다.

**Comment by miercat0424** [comment]
1. powershell에서 wsl --list --verbose 로 Ubuntu WSL2 버전 확인
________________________________________________________________________________________________________________________________
WSL2 에서 Gazebo 실행 시 필요한 파일 
[https://www.youtube.com/watch?v=DW7l9LHdK5c&t=170s](url)
________________________________________________________________________________________________________________________________
이후 bashrc 편집
sudo nano $HOME/.bashrc
(맨아랫줄에)
export GAZEBO_IP=127.0.0.1
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0 
export LIBGL_ALWAYS_INDIRECT=0
________________________________________________________________________________________________________________________________
