### ISSUE TITLE
[BUG] : ROS2 윈도우 설치과정 오류

### ISSUE THREAD

**Issue by sinnara2021** [Road-Balance/gcamp_ros2_basic#14]
# **What happened? 어떤 문제가 생겼는지 상세히 기술해주세요.**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)

## **To Reproduce 실행한 프로그램 및 커멘드 라인**
C:\gcamp_ros2_ws> ros2 launch gcamp_gazebo gcamp_world_windows.launch.py

## **Expected behavior 예상한 결과**
왜 실행 자체가 안될까요? 음 먼가 막아져 있는걸까요?

## **Screenshots 스크린샷**
![image](https://user-images.githubusercontent.com/79739569/155202745-b9e97414-779d-4116-9362-cdd7cc2a8959.png)
install\setup.bat  이 안먹음..

![image](https://user-images.githubusercontent.com/79739569/155198713-13b883d4-c086-4218-9076-83fe5176853c.png)
실행이 되지 않음.

![image](https://user-images.githubusercontent.com/79739569/155202945-bbeecd10-f4ab-4498-b3b2-93c84a24c6d0.png)
gcamp_gazebo 파일을 찾을수 없다고 뜨네요.

## **Environment 사용환경**
 - OS Version : 
 - ROS Version :

### **충분한 리서치 없이 무분별한 Issue는 삭제됩니다.**
이슈를 만들기 전에...
- [ ] 구글링을 통해 충분한 검색을 해보았다. *
- [ ] Repo내 같은 이슈가 존재하는지 확인해 보았다. *
- [ ] 문제 해결을 위해 이슈에 충분한 정보를 제공하였다. *

**Comment by kimsooyoung** [comment]
1. 동일한 파일이 중복되어 존재하는 것 같습니다. _첫번째 사진 참고_ 
`src/gcamp_ros2_basic`을 제외하고 모두 삭제해주세요.

2. install 폴더 내 위치한 파일들 중 `setup.bat`이 존재하는지 확인 부탁드립니다.

3. gcamp_gazebo가 정위치에 존재하지 않아 빌드가 되지 않았고, 따라서 찾을 수 없게 된 상황입니다.

현재 제공해주신 정보로 답변 드릴 수 있는 내용은 위와 같습니다.

## 제가 만들어 둔 issue 포멧에 따라 올바른 정보를 기입 부탁드립니다.

이 포멧은 제가 멋으로 만들어 둔 것이 아닙니다. 
다른 분들께서도 검색하여 찾으실 수 있도록 

1. 올바른 제목과
2. 사용 환경에 대한 정보도 추가를 부탁드리며, 
3. 현재까지 진행한 내용, 
4. 시도해본 내용과 같은 정보를 추가하여 다시 작성 부탁드립니다.

**Comment by sinnara2021** [comment]
1. src/gcamp_ros2_basic모두 삭제 하였습니다.
2. setup.bat 파일이 존재하지 않습니다.
3. gcamp_gazebo 폴더는 C:\gcamp_ros2_ws\gcamp_ros2_basic 에 있습니다.

**Comment by sinnara2021** [comment]
우선 답변 감사드립니다. 한번 다시 점검해보고 정확하게 한번 다시 글 작성 하여 보도록 하겠습니다. ^^ 오늘 저녁은 무조건 해결되면 좋겠습니다.
