### ISSUE TITLE
[BUG] :  odome실행 오류_ 중간 프로젝트 - Maze World

### ISSUE THREAD

**Issue by jyes90** [Road-Balance/gcamp_ros2_basic#17]
# **What happened? 어떤 문제가 생겼는지 상세히 기술해주세요.**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)

ros2 run py_action_pkg odome_sub_node코드를 실행햇을 때 
No executable found
오류가 발생하여 
ros2 run py_action_pkg odome_sub_node에서
e를 제외한 ros2 run py_action_pkg odom_sub_node로 변경하여 실행은 가능하나, 
원인을 파악하고자 합니다.  

파일을 수정하거나 이동을 한적이 없으나 오류가 발생하였습니다. 
어느부분이 잘못된건지  확인 부탁드리겠습니다.

## **To Reproduce 실행한 프로그램 및 커멘드 라인**

ros2 run py_action_pkg odome_sub_node

## **Environment 사용환경**

- OS Version : linux 20.04
 - ROS Version : ros2 foxy
 - 
## **Relevant log output (관련 로그 output을 적어주세요)**

No executable found

### **충분한 리서치 없이 무분별한 Issue는 삭제됩니다.**
이슈를 만들기 전에...
- [v] 구글링을 통해 충분한 검색을 해보았다. *
- [v] Repo내 같은 이슈가 존재하는지 확인해 보았다. *
- [v] 문제 해결을 위해 이슈에 충분한 정보를 제공하였다. *

**Comment by kimsooyoung** [comment]
**확인 결과 단순 오타로 추정됩니다.** 

`e`를 제외하시고 `ros2 run py_action_pkg odom_sub_node`로 실행하시면 문제는 없나요?


이러한 이름은 `setup.py` 파일 내 `entry_points`로 지정되어 있습니다.
아래 코드를 참고 부탁드립니다.
```python3
    entry_points={
        'console_scripts': [
            'fibonacci_action_server        = py_action_pkg.fibonacci_action_server:main',
            'fibonacci_action_server_cancel = py_action_pkg.fibonacci_action_server_cancel:main',
            'fibonacci_action_client        = py_action_pkg.fibonacci_action_client:main',
            'fibonacci_action_client_cancel = py_action_pkg.fibonacci_action_client_cancel:main',
            'maze_action_server             = py_action_pkg.maze_action_server:main',
            'maze_action_client             = py_action_pkg.maze_action_client:main',
            'img_subscriber_node            = py_action_pkg.image_sub:main',
            'odom_sub_node                  = py_action_pkg.odom_sub:main',
            'robot_controller               = py_action_pkg.robot_controller:main',
        ],
    },
```

현재 실행을 위한 진입점(=entry_points)들이 여러개 정의되어 있습니다. 

이 중 우리가 사용할 것은 `odom_sub_node`이며, 실질적으로는 
* **py_action_pkg**이라는 패키지 내에서 
* **odom_sub**이라는 파이썬 파일에 접근하여
* **main**이라는 함수를 시작하라는 뜻이 됩니다.

**Comment by jyes90** [comment]
감사합니다. 

e를 제외하고 실행시에는 문제없이 구동됩니다.
