### ISSUE TITLE
src 폴더 내부 정리하기

### ISSUE THREAD

**Issue by ftatp** [Road-Balance/gcamp_ros2_basic#18]
src 폴더 내부에 패키지들이 너무 많을 경우, 이들을 정리하기 위해 비슷한 패키지들끼리 상위 폴더 아래로 배치하면 빌드시 에러가 발생합니다. 이 경우에 어떻게 해야하나요?

예를 들면 아래와 같이 cpp_svrcli와 py_svrcli를 test_svrcli로 묶어서 관리하려고 하는데 빌드시 Cmake 파일에서 여전히 {workspace경로}/src/cpp_svrcli를 찾으려고 하고 있습니다.

정리하기 전
![Screenshot from 2022-03-19 16-48-23](https://user-images.githubusercontent.com/22390526/159112813-adbf6813-139a-44db-b144-5200198bc1e2.png)

정리한 후
![Screenshot from 2022-03-19 17-01-23](https://user-images.githubusercontent.com/22390526/159113077-bd1ad5af-c86f-4b0f-bc8a-638f4f7a2229.png)

=> CMake Error: The source directory "/home/ftatp/Documents/ROS/src/cpp_srvcli" does not exist.

**Comment by kimsooyoung** [comment]
집 주소가 바뀌면 택배가 제대로 오지 않듯이, 폴더 구조를 바꾸시면 **다시 빌드를 통해 경로를 재설정** 해주셔야 합니다. 

간랸하게, `build` 폴더와, `install` 폴더를 모두 삭제하신 뒤, 다시 전체 `colcon build`를 해주시면 됩니다.

```bash
cd <your-ws-folder>
rm -rf build
rm -rf install
colcon build
```
