### ISSUE TITLE
CMake Error at CMakeLists.txt:23 (find_package)

### ISSUE THREAD

**Issue by opensupport-ceo** [Road-Balance/gcamp_ros2_basic#2]
I've been following this "[https://puzzling-cashew-c4c.notion.site/Gazebo-Simulation-a005ee3fa0cb45f19f86cc5d89ca4f1f](https://puzzling-cashew-c4c.notion.site/Gazebo-Simulation-a005ee3fa0cb45f19f86cc5d89ca4f1f)" and "[https://www.youtube.com/watch?v=JoDKs1Vw2NY&list=PLieE0qnqO2kTNCznjLX_AaXe2hNJ-IpVQ&index=4](https://www.youtube.com/watch?v=JoDKs1Vw2NY&list=PLieE0qnqO2kTNCznjLX_AaXe2hNJ-IpVQ&index=4)"

Here, I've tried to do.

# 폴더 이름을 직접 타이핑하지 마시고 Tab키를 적극 사용하시기를 권장합니다.
$ cd gcamp_ros2_ws/src
$ git clone https://github.com/Road-Balance/gcamp_ros2_basic.git

$ cd ~/gcamp_ros2_ws/
# 프로젝트 패키지 빌드
$ cbp gcamp_gazebo

When I've tried to do "$ cbp gcamp_gazebo", I got the error below:
'''
bini@ZEUS:~/gcamp_ros2_ws$ cbp gcamp_gazebo
Starting >>> gcamp_gazebo
--- stderr: gcamp_gazebo                         
CMake Error at CMakeLists.txt:23 (find_package):
  By not providing "Findxacro.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "xacro", but
  CMake did not find one.

  Could not find a package configuration file provided by "xacro" with any of
  the following names:

    xacroConfig.cmake
    xacro-config.cmake

  Add the installation prefix of "xacro" to CMAKE_PREFIX_PATH or set
  "xacro_DIR" to a directory containing one of the above files.  If "xacro"
  provides a separate development package or SDK, be sure it has been
  installed.

---
Failed   <<< gcamp_gazebo [0.66s, exited with code 1]

Summary: 0 packages finished [0.84s]
  1 package failed: gcamp_gazebo
  1 package had stderr output: gcamp_gazebo

'''
I think it seems to be a error related to CMAKE environment.
Then, pleaselet us know how to fix this error.

**Comment by kimsooyoung** [comment]
Since There's Few Information, Cannot recognize problem.

Add more info as I mentioned to you through e-mail.

**Comment by opensupport-ceo** [comment]
I installed ROS-Foxy via [https://puzzling-cashew-c4c.notion.site/ROS-2-Foxy-Linux20-04-58f0c6f2537e498eb8fe163ad1f13ce5](https://puzzling-cashew-c4c.notion.site/ROS-2-Foxy-Linux20-04-58f0c6f2537e498eb8fe163ad1f13ce5).

In short,
Env.: Ubuntu 20.10, ROS-Foxy-desktop

and then as I reported in the previous, I got the error when I run "$ cbp gcamp_gazebo".

Let us know whether there's more information you have to know, related to my env..

**Comment by kimsooyoung** [comment]
How did you install xacro?
Did you install with `apt`?

for example
```bash
$ sudo apt-get install ros-foxy-xacro 
```

Plz Share your log with exact commands

**Comment by vd9hosigi6** [comment]
### xacro 컴파일 오류 해결 방법입니다.   

gcamp_gazeo 컴파일 시 다음과 같은 오류가 발생합니다.  
```sh
$ colcon build --symlink-install --packages-select gcamp_gazebo  
```
![xacro_error01](https://user-images.githubusercontent.com/88458440/136839571-436643fe-89cc-4074-83cf-b18708bfe732.jpg)  

오류가 발생한 이유는 xacro 패키지를 설치하지 않았기 때문입니다.  
xacro 는 다음과 같이 설치할 수 있습니다.  
```sh   
$ sudo apt install ros-foxy-xacro  
```   
그런데 xacro 를 설치한 후에도 여전히 같은 문제가 발생하는 경우 다음 명령을 실행해야 합니다.   
참고로 ROS 2 를 패키지를 다운 받아 설치하지 않고 직접 빌드하여 사용하고 있는 사람들의 경우 이런 문제가 발생합니다.  

```sh
$ source /opt/ros/foxy/share/xacro/local_setup.bash
```   

그리고 새로 빌드하면 성공적으로 빌드됩니다.  
```sh
$ colcon build --symlink-install --packages-select gcamp_gazebo  
```
![xacro_error02](https://user-images.githubusercontent.com/88458440/136843062-8e83f5b6-b472-466c-a2ab-a188521a15f7.jpg)   

그런 후 ~/.gazebo/gui.ini 파일을 다음과 같이 수정합니다.   

```ini
[model_paths]   
filenames=/home/hp/ros2_ws/src/gcamp_ros2_basic/gcamp_gazebo/GazeboFiles/models   
```   

그리고 gcamp_gazebo 를 실행합니다.   
```sh
$ ros2 launch gcamp_gazebo gcamp_world.launch.py
```

컴퓨터 사양에 따라 처음 실행 시 약 5분 정도 걸릴 수 있으니 기다리면 다음과 같은 화면이 나옵니다.   

![xacro_error03](https://user-images.githubusercontent.com/88458440/136843700-ddda566c-0889-4dc8-bde5-a8da112e9569.jpg)

**Comment by kimsooyoung** [comment]
Closed because it has been resolved and there is no reply for a long time.
