### ISSUE TITLE
[BUG] : ROS2 윈도우에서의 개발환경구축

### ISSUE THREAD

**Issue by sy460129** [Road-Balance/gcamp_ros2_basic#68]
# **What happened? 어떤 문제가 생겼는지 상세히 기술해주세요.**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)
ros2 launch gcamp_gazebo gcamp_world_windows.launch.py

gazebo가 실행되면서 로봇의 파일은 보입니다.. 다만 움직이지 않습니다..

![colcon_err](https://user-images.githubusercontent.com/78065521/200825843-65503a64-88be-48e0-9b4f-d4c3d43f64ef.png)

이것은 예제 실행을 위해 필요한 package-build 과정 중 두 번째 코드인
colcon build --symlink-install --packages-select py_service_pkg
을 실행시켰을 때의 모습입니다.

C:\opt\ros\foxy\x64\tools\vcpkg\installed\x64-windows가 없다는 문구와 함께 에러가 떴습니다..

그래서 아래 스크린샷은 제가 설정한 환경변수와 실제 C드라이브에서 vxpkg까지 들어간 후의 모습입니다.
![empty_file](https://user-images.githubusercontent.com/78065521/200826354-c3a562f4-0568-4b96-b237-2b2504b4cf6a.png)

![환경변수](https://user-images.githubusercontent.com/78065521/200826366-bfa4cab8-b2e4-4653-8efa-f213e9a18607.png)

만약 환경변수 설정이 잘못된 것이 아니고 있어야 할 installed\x64-windows가 없는 것이라면 어디가 문제였는지 알려주시면 감사하겠습니다..

아래는 최종적으로 실행 한 후의 모습입니다.

![실행_err](https://user-images.githubusercontent.com/78065521/200826570-a2766b7e-e66d-4fb4-b349-5b71ab0f32c3.png)

좌측 터미널 하단을 보시면 process has died라고 뜨는데, 이것 때문에 움직이지 않는다고 생각합니다..

## **Environment 사용환경**
 - OS Version : Windows 11
 - ROS Version :

**Comment by kimsooyoung** [comment]
시간이 오래 지나 issue를 닫겠습니다. 윈도우 개발 과정은 wsl 사용으로 대체 강의를 제작하여 업로드하겠습니다.
