### ISSUE TITLE
[BUG] : 실습을 위한 Gazebo Simulation 소개 // 환경 구성의 cbp gcamp_gazebo 부분

### ISSUE THREAD

**Issue by jungwoonghyun** [Road-Balance/gcamp_ros2_basic#69]
# **What happened? 어떤 문제가 생겼는지 상세히 기술해주세요.**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)
![질문캡처](https://user-images.githubusercontent.com/105268153/202373396-b359f2e3-f664-405d-8e4e-cbeaf65619e7.PNG)

다음과 같이 실행해 cbp gcamp_gazebo를 실행하였는데 

![캡처1](https://user-images.githubusercontent.com/105268153/202373828-92ea3fba-9ca8-4773-8dc0-0f572f1dde52.PNG)

다음과 같이 커맨드 cbp를 찾을수 없다고 합니다.

## **To Reproduce 실행한 프로그램 및 커멘드 라인**

다른 커맨드들을 실행해보았는데 딱히 고쳐지진 않았습니다. 모든 커맨드를 시도해보진 않았습니다.

## **Expected behavior 예상한 결과**

colcon build successful을 예상했습니다.

## **Environment 사용환경**
 - OS Version :  Linux  20.04
 - ROS Version : foxy

**Comment by kimsooyoung** [comment]
![image](https://user-images.githubusercontent.com/12381733/202787079-8cc0c1a1-41b7-4839-8ed9-3b4dbd49fa5f.png)
환경 설정 강의의 `bashrc` 수정 과정을 적용하셔야 합니다. :)
