### ISSUE TITLE
[BUG] : ros2 launch gcamp_gazebo gcamp_world.launch.py  커맨드 실행 시 frame 문제로 인한 gazebo 출력 실패

### ISSUE THREAD

**Issue by bert13069598** [Road-Balance/gcamp_ros2_basic#70]
# **What happened? 어떤 문제가 생겼는지 상세히 기술해주세요.**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)

## **To Reproduce 실행한 프로그램 및 커멘드 라인**
https://puzzling-cashew-c4c.notion.site/Gazebo-Simulation-a005ee3fa0cb45f19f86cc5d89ca4f1f
해당 링크에서 실습을 진행하다가 
ros2 launch gcamp_gazebo gcamp_world.launch.py 
를 실행한 결과 

[ros2-5] Warning: Invalid frame ID "front_left_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp
[ros2-5] Warning: Invalid frame ID "front_right_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp
[ros2-5] Warning: Invalid frame ID "back_left_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp
[ros2-5] Warning: Invalid frame ID "back_right_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp

아래와 같은 문구가 반복적으로 출력되면서 gazebo가 출력되지 않습니다.
gazebo는 gazebo11.desktop is no responding 이런식으로 팝업창이 계속 뜹니다.

경로 확인도 여러번 하였고 gcamp_world.launch.py 내부 소스도 확인해보았지만 원인을 파악하지 못하였습니다.
현재 ubuntu내에 ros2만 가동하는 것이 아니기에 기존과는 약간 다르게 폴더를 생성하였습니다.
![Screenshot from 2022-11-19 22-38-55](https://user-images.githubusercontent.com/89738612/202853496-f9cdb889-d8ac-4868-9c78-ea8b701ef883.png)
![Screenshot from 2022-11-19 22-39-47](https://user-images.githubusercontent.com/89738612/202853498-18a98ae1-0b48-46fe-b63e-b1f5023eec45.png)

위와 같이 생성하여 test_ros2_ws 내에서 진행을 하려 시도 중입니다.
다른 것도 안되나해서 maze_world를 작동한 결과 정상 작동합니다.
https://puzzling-cashew-c4c.notion.site/ROS-2-Launch-launch-file-55c2125808ef4b64bade278852b37d6e
위 링크에 나온 gcam_world.launch.py와 현재 깃허브 내의 소스가 다른 것을 확인하여 위 링크의 소스를 넣어 작동하였지만 정상작동에 실패하였습니다.

먼저 해당 문제를 해결하신 분이 있다면 도움 부탁드립니다.
감사합니다.
## **Expected behavior 예상한 결과**
Gazebo와 Rviz의 정상작동
## **Screenshots 스크린샷**
![Screenshot from 2022-11-19 13-19-29](https://user-images.githubusercontent.com/89738612/202853195-c07d713e-c963-4e9f-a9ec-46f1067532eb.png)

## **Environment 사용환경**
 - OS Version : Ubuntu 20.04
 - ROS Version : ROS2 Foxy

### **충분한 리서치 없이 무분별한 Issue는 삭제됩니다.**
이슈를 만들기 전에...
- [x] 구글링을 통해 충분한 검색을 해보았다. *
- [x] Repo내 같은 이슈가 존재하는지 확인해 보았다. *
- [x] 문제 해결을 위해 이슈에 충분한 정보를 제공하였다. *

**Comment by kimsooyoung** [comment]
아래 코드와 같이 gcamp_world.launch.py에서 spawn_entity를 주석처리 한 뒤 실행하면 어떤 결과가 나오나요? 

[참고 링크](https://github.com/Road-Balance/gcamp_ros2_basic/blob/390f79a8e6d5bfaca2326f00b9ea03cd638e8dfd/gcamp_gazebo/launch/gcamp_world.launch.py#L81)

```python3
    return LaunchDescription(
        [
            TimerAction(
                period=3.0,
                actions=[rviz_start]
            ),
            # start gazebo, notice we are using libgazebo_ros_factory.so instead of libgazebo_ros_init.so
            # That is because only libgazebo_ros_factory.so contains the service call to /spawn_entity
            # ExecuteProcess(
            #     cmd=["gazebo", "--verbose", world_path, "-s", "libgazebo_ros_factory.so"],
            #     output="screen",
            # ),
            start_gazebo_server_cmd,
            start_gazebo_client_cmd,
            robot_state_publisher_node,
            # tell gazebo to spwan your robot in the world by calling service
            # spawn_entity, => 이 부분 주석
        ]
    )
```

**Comment by bert13069598** [comment]
gazebo 출력은 정상적으로 되고 로봇 생성은 되지 않습니다!
터미널의 warning 또한 그대로 출력됩니다.
![Screenshot from 2022-11-20 11-06-58](https://user-images.githubusercontent.com/89738612/202879293-0f9ef9c9-c6ac-4a17-a6be-90ab7359f17e.png)
![Screenshot from 2022-11-20 11-06-50](https://user-images.githubusercontent.com/89738612/202879294-4e70e940-d9e4-443d-82a4-f3cf4346535b.png)
![Screenshot from 2022-11-20 11-07-03](https://user-images.githubusercontent.com/89738612/202879299-24d274d8-9caa-4515-8715-55cbfed4cb8c.png)

**Comment by Jeong-hun-Park** [comment]
저도 똑같은 문제로 헤매고 있는데 혹시 해결하셨나요...?

**Comment by kimsooyoung** [comment]
말씀주신 오류를 해결해두었습니다. 

시간이 지체되어 죄송하며 다시 시도해보신 뒤 문제가 있다면 알려주세요!!

**Comment by bert13069598** [comment]
신경 써주셔서 감사합니다!!
