### ISSUE TITLE
[Feature Request] : skidbot 과 diffbot의 odometry_pose 값의 차이점에 관한 질문입니다.

### ISSUE THREAD

**Issue by sangyomi** [Road-Balance/gcamp_ros2_basic#73]
**Is your feature request related to a problem? Please describe.**

안녕하세요, skidbot의 odometry 값을 이용하여 skidbot의 절대좌표를 알고 싶습니다.
skidbot의 odometry의 pose 값은 다시 원점으로 돌아왔을 때 (0, 0) 의 값을 유지하지 않고, 자신의 절대적 위치 좌표를 나타내지 않는 것을 확인하였습니다.
그러나 diffbot의 odometrt의 pose 값은 원점으로 다시 돌아 왔을 때 (0,0) 의 값을 유지하였고, 항상 자신의 위치를 절대좌표로 나타냈습니다.
두 로봇의 차이점을 찾기 위해서 파일을 탐색하여 보았으나 원하는 바는 찾지 못하였습니다.'

또한 두 로봇의 라이다 최대 거리 측정 값도 Rviz 상에서는 다르게 나타나는 것을 확인할 수 있었습니다.

결론적으로 skidbot의 odometry 값을 diffbot의 odometry 값처럼 정확하게 나오게 바꾸고 싶습니다.
답변주시면 정말 감사하겠습니다.

**Comment by kimsooyoung** [comment]
현재 사옹되고 있는 gazebo상 로봇의 odometry는 gazebo의 plugin을 사용하여 제작되었습니다.

더불어 어떠한 상황에서 실험을 하셨을지 모르겠지만 diffbot의 odometry도 지속적으로 로봇을 이동시키면 조금씩 틀어지기 시작할 것입니다.

따라서 로보틱스에서는 바퀴 움직인에 의존하여 odometry를 추출하기보다, 다른 센서를 결합하여 보다 정확한 위치를 판별합니다.

알고리즘적으로 이러한 내용을 구현해보시거나, 아래 링크를 통해 사용되고 있는 gazebo plugin에 대해서 공부해보세요.

https://github.com/rticommunity/gazebo-dds-plugins/blob/master/src/skid_steer_drive/README.md
