### ISSUE TITLE
[BUG] : Colcon을 이용한 빌드 과정에서 생기는 오류

### ISSUE THREAD

**Issue by jhm1313** [Road-Balance/gcamp_ros2_basic#74]
ROS2 강의 2강에서 colcon을 이용한 빌드 과정에서 아래와 같이 커맨드를 입력하였으나, 오류가 생기는 것을 확인하였습니다.
![스크린샷, 2023-02-06 21-51-55](https://user-images.githubusercontent.com/44698831/217154969-6b9bcee4-0d4a-4a24-bc9c-838c7e922007.png)

em 모듈이 없다는 에러 메시지를 확인하여 구글링한대로 `pip3 install empy`, `sudo apt-get install python3-empy` 등의 커맨드를 입력해보았으나 해결되지 않아 계속 해결 방법을 찾던 중,
[이곳](https://stackoverflow.com/questions/74934600/modulenotfounderror-no-module-named-em-despite-empy-being-installed-when-usin)에 올라온 에러와 비슷한 에러임을 확인할 수 있었습니다.

해당 내용에 따르면 ros2에서 인식하는 파이썬의 path(/opt/ros/foxy/lib/python3.8/)와 제 컴퓨터에 있는 파이썬 path(/usr/local/lib/python3.8)가 달라 충돌이 생기는 것으로 추측되지만 어떻게 해결해야될지 감이 안 잡힙니다.

시도해볼만한 해결법이 있다면 도움을 주시면 정말 감사하겠습니다.

## **Environment 사용환경**
 - OS Version : Ubuntu 20.04
 - ROS Version : foxy

### **충분한 리서치 없이 무분별한 Issue는 삭제됩니다.**
이슈를 만들기 전에...
- [ V ] 구글링을 통해 충분한 검색을 해보았다. *
- [ V ] Repo내 같은 이슈가 존재하는지 확인해 보았다. *
- [ V ] 문제 해결을 위해 이슈에 충분한 정보를 제공하였다. *

**Comment by kimsooyoung** [comment]
혹시 해결 하셨을까요?
