### ISSUE TITLE
src 없이 package build

### ISSUE THREAD

**Issue by yomamdde** [Road-Balance/gcamp_ros2_basic#76]
안녕하세요 
my_ws/src 처럼 src 폴더를 만들지 않고 

my_ws 
 ㄴmy_pkg1
 ㄴmy_pkg2
 ㄴinstall
 ㄴbuild

이런 형식으로 워크스페이스 구성를 구성하고 빌드하는것이 가능한지 궁금합니다.

**Comment by kimsooyoung** [comment]
불가합니다.
ros2에서 사용되는 colcon 빌드 시스템은 src라는 폴더의 존재에 따라 해당 폴더가 workspace인지를 판단합니다.
아래는 colcon의 공식 문서 중 발췌한 내용입니다.

![image](https://user-images.githubusercontent.com/12381733/225819061-9402b37d-2275-459f-992b-1ec66349fe4b.png)

* image from [colcon.readthedocs](https://colcon.readthedocs.io/en/released/user/what-is-a-workspace.html)
