### ISSUE TITLE
Gazebo package error Failed to load plugin libgazebo_ros_factory.so: libgazebo_ros_factory.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ftatp** [Road-Balance/gcamp_ros2_basic#8]
강의 4강에서 gazebo를 설치하고 

`ros2 launch gcamp_gazebo gcamp_world.launch.py`

를 실행하였을 때 다음과 같이 플레이어 오브젝트 및 메인 카메라가 보이지 않게 됩니다.

![Screenshot from 2022-01-17 16-06-41](https://user-images.githubusercontent.com/22390526/150140878-ee6cd4ef-0e16-4362-a70d-c84207817755.png)

실행시 로그 상 제일 상단에 나타나는 에러 문구는 다음과 같습니다.

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
`[gazebo-2] [1;31m[Err] [Plugin.hh:212] [0m[1;31mFailed to load plugin libgazebo_ros_factory.so: libgazebo_ros_factory.so: cannot open shared object file: No such file or directory
[gazebo-2] [0m[1;31m[Err] [Master.cc:96] [0m[1;31mEXCEPTION: [0m[1;31mUnable to start server[bind: Address already in use]. There is probably another Gazebo process running.
[gazebo-2] [0m[1;31m
[gazebo-2] [0m[1;31m[0m[1;31m[Err] [Master.cc:96] [0m[1;31mEXCEPTION: [0m[1;31mUnable to start server[bind: Address already in use]. There is probably another Gazebo process running.
[gazebo-2] [0m[1;31m
[ERROR] [gazebo-2]: process has died [pid 8494, exit code 255, cmd 'gazebo --verbose /home/ftatp/Documents/test_ros2_ws/install/gcamp_gazebo/share/gcamp_gazebo/worlds/gcamp_world.world -s libgazebo_ros_factory.so'].
[gazebo-2] [1;36m[0m[1;32m[0m
[gazebo-2] [0m[1;31m[0m[1;33m[0m[1;31m[0m
[ros2-3] Traceback (most recent call last):
[ros2-3]   File "/opt/ros/foxy/bin/ros2", line 11, in <module>
[ros2-3]     load_entry_point('ros2cli==0.9.10', 'console_scripts', 'ros2')()
[ros2-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
[ros2-3]     rc = extension.main(parser=parser, args=args)
[ros2-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/ros2service/command/service.py", line 41, in main
[ros2-3]     return extension.main(args=args)
[ros2-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/ros2service/verb/call.py", line 58, in main
[ros2-3]     return requester(
[ros2-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/ros2service/verb/call.py", line 69, in requester
[ros2-3]     module = importlib.import_module('.'.join(parts[:-1]))
[ros2-3]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[ros2-3]     return _bootstrap._gcd_import(name[level:], package, level)
[ros2-3]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[ros2-3]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[ros2-3]   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
[ros2-3]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ros2-3]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[ros2-3]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[ros2-3]   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[ros2-3] ModuleNotFoundError: No module named 'gazebo_msgs'`
[ERROR] [ros2-3]: process has died [pid 8496, exit code 1, cmd 'ros2 service call /spawn_entity gazebo_msgs/SpawnEntity {name: "skidbot", xml: "<?xml version=\"1.0\" ?>

--- 이후 xml 전문--
<robot name=\"skidbot\">
</robot>

--- 이후 다음 warning의 반복---
[ros2-4] [INFO] [1642259216.740639566] [rviz2]: Stereo is NOT SUPPORTED
[ros2-4] [INFO] [1642259216.740738290] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[ros2-4] [INFO] [1642259216.823040770] [rviz2]: Stereo is NOT SUPPORTED
[ros2-4] [INFO] [1642259217.021575807] [rviz2]: Stereo is NOT SUPPORTED
[ros2-4] Parsing robot urdf xml string.
[ros2-4] Warning: Invalid frame ID "back_left_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-4]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.12/src/buffer_core.cpp
[ros2-4] Warning: Invalid frame ID "back_right_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-4]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.12/src/buffer_core.cpp
[ros2-4] Warning: Invalid frame ID "front_left_wheel" passed to canTransform argument source_frame - frame does not exist
[ros2-4]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.12/src/buffer_core.cpp
[ros2-4] Warning: Invalid frame ID "front_right_wheel" passed to canTransform argument source_frame - frame does not exist

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

사용 환경 : Ubuntu 20.04, ros-foxy, Gazebo11, 가상환경 x
시도할 수 있는 방법은 많이 없어서 ros와 gazebo를 완전히 삭제하고 다시 설치 해보았습니다.
Address is already used를 보니 내부에서 로컬 주소로 서버를 여는 것 같아서 혹시 이미 gazebo를 실행시키고 있나 싶어 재부팅해서 런치를 해보았습니다. 파이썬 버전도 살짝 의심이 됩니다만 강의에서 어떠한 파이썬 버전을 사용했는지 알 수 없어서 건드리지 않고 있습니다.

무엇을 놓치고 있을까요?

**Comment by kimsooyoung** [comment]
정확히 어떤 문제인지는 확인하지 못하였지만 

오류가 발생할 여지가 있는 부분을 수정하였습니다. 

다시 한 번 launch를 실행시켜 보시고 피드백 부탁드립니다.

![image](https://user-images.githubusercontent.com/12381733/150271479-dc5034d5-1c16-4029-a0ee-22dd2d07ed37.png)

**Comment by ftatp** [comment]
답변 감사합니다!

이번에는 실행해보니 다음과 같은 에러가 뜹니다

[gazebo-3] [Err] [Plugin.hh:212] Failed to load plugin libgazebo_ros_factory.so: libgazebo_ros_factory.so: cannot open shared object file: No such file or directory
[ERROR] [gazebo-3]: process[gazebo-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gazebo-3]: sending signal 'SIGTERM' to process[gazebo-3]
[ERROR] [gazebo-3]: process has died [pid 5176, exit code -15, cmd 'gazebo --verbose /home/ftatp/gcamp_ros2_ws/install/gcamp_gazebo/share/gcamp_gazebo/worlds/gcamp_world.world -s libgazebo_ros_factory.so'].
[gazebo-3] 

이후 원래 나타났었던 xml과 wheel 관련 warning은 나타나지 않고 launch 자체가 종료되었습니다.
![Screenshot from 2022-01-20 21-20-26](https://user-images.githubusercontent.com/22390526/150337632-4808acb1-ec3b-4f03-9453-64443796f4f7.png)

**Comment by kimsooyoung** [comment]
피드백 감사합니다.

```
LookupError: Could not find the resource 'gazebo_ros' of type 'packages'
```

이 부분으로 미루어 보아 gazebo_ros 패키지가 설치되어 있지 않은 것으로 예상됩니다. 

번거롭지만 다음 커멘드 라인을 통해 해당 패키지를 설치하신 뒤 다시 한 번 시도를 부탁드립니다.

```
sudo apt install ros-foxy-gazebo-ros
```

**Comment by ftatp** [comment]
감사합니다!!

gazebo_ros를 설치하니 문제가 factory.so에 관한 문제가 해결되었습니다!
![Screenshot from 2022-01-21 20-45-03](https://user-images.githubusercontent.com/22390526/150521777-301f06c3-3e03-45be-b300-1ff605dfe6e9.png)

그런데 해결하면서 rviz가 실행이 되지 않게 되었습니다. 다음과 같은 에러가 발생합니다.

`[gazebo-3] [Err] [Plugin.hh:212] Failed to load plugin libgazebo_ros_camera.so: libgazebo_ros_camera.so: cannot open shared object file: No such file or directory
[gazebo-3] [Err] [Plugin.hh:212] Failed to load plugin libgazebo_ros_ray_sensor.so: libgazebo_ros_ray_sensor.so: cannot open shared object file: No such file or directory
[gazebo-3] [Err] [Plugin.hh:212] Failed to load plugin libgazebo_ros_diff_drive.so: libgazebo_ros_diff_drive.so: cannot open shared object file: No such file or directory
[spawn_entity.py-4] [INFO] [1642765398.627738667] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [skidbot]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 6213]
`

혹시 이것도 다른 무언가를 설치 안해서 생겨난 문제일까요?

**Comment by kimsooyoung** [comment]
저도 정확한 진단은 내리지 못할 것 같습니다. 초기화와 설치가 이어지다보니 환경이 꼬인 것 같습니다.

우선 다음 링크대로 시도해보시고, 추가 구글링을 해보시겠어요?

* [Failed to load plugin (gazebo-11)](https://answers.gazebosim.org//question/25906/failed-to-load-plugin-gazebo-11/) 

```
source /opt/ros/foxy/setup.bash
```

**Comment by ftatp** [comment]
감사합니다. 

처음부터 환경을 전부 초기화시킨 다음 다시 해봤더니 아까와 같은 카메라 에러 log는 나타나지 않지만, 대신에 

`[gazebo-3] [Msg] Loading world file [/home/ftatp/gcamp_ros2_ws/install/gcamp_gazebo/share/gcamp_gazebo/worlds/gcamp_world.world]
[gazebo-3] Error [Param.cc:449] Invalid argument. Unable to set value [world ] for key[odometry_source].`

한줄만 붉게 나타나는 상황까지 진행되었습니다. 여전히 rviz는 나타나지 않는 상황입니다만, teleop_twist_keyboard가 정상적으로 동작하고 있기 때문에 우선은 다음 강의로 넘어가고자 합니다.

그런데 해당 템플릿은 어디서 확인할 수 있을까요? 이후 강의를 진행하다가 해당 버그 리포트 템플릿을 이용해보겠습니다!

**Comment by kimsooyoung** [comment]
확인하였습니다. 

아마 world 다음 불필요한 공백이 존재하여 그런 것 같은데요. 저도 다시 살펴보겠습니다.
기존 강의를 청취하시는 분들이 곧바로 바꾸기보다 제 주변 분들께도 확인을 부탁드린 후 검증이 된 상태에서 업데이트를 하겠습니다.

이슈 템플릿은 Issues => 초록색 New issue 버튼 클릭 시 자동으로 보여지게 되어있습니다. 

피드백 감사드리며 추가 버그가 있을 시 주저마시고 또 이슈 올려주세요 :)
